[tool.poetry]
name = "nul-rdc-scripts"
version = "0.1.0"
description = "Scripts for NUL RDC Digitization Team"
authors = [
    "Northwestern University Libraries <repository@northwestern.edu>",
    "Sophia Francis",
    "Alec Bertoy",
    "Joshua Yocum (until Oct 2022)",
]
packages = [{include = "nulrdcscripts"}]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
colorama = "^0.4.6"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
aproc = 'nulrdcscripts.aproc.aproc:main'
vproc = 'nulrdcscripts.vproc.vproc:main'
ingest = 'nulrdcscripts.ingest.ingest:main'
avqc = 'nulrdcscripts.avqc.avqc:main'
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"