[tool.poetry]
name = "nul-rdc-scripts"
version = "0.1.0"
description = "Scripts for NUL RDC Production Team"
authors = ["Your Name <you@example.com>"]
packages = [{include = "nulrdcscripts"}]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
aproc = 'nulrdcscripts.aproc.aproc:main'
vproc = 'nulrdcscripts.vproc.vproc:main'
ingest = 'nulrdcscripts.ingest.ingest:main'
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
