# Many thanks to Code First with Hala on Youtube for her video Tkinter Data Entry Form tutorial for beginners - Python GUI project [responsive layout]

import tkinter as tkin
from tkinter import scrolledtext

window = tkin.Tk()
window.title("Error Entry Form")

frame = tkin.Frame(window)
frame.pack()

#Saving video Information

# Setting up labels
video_info_frame=tkin.LabelFrame(frame, text="Video Information",padx=20,pady=20)
video_info_frame.pack(fill=tkin.BOTH,expand=True)
video_title=tkin.Label(video_info_frame, text="Video Title")
video_title.grid(row=0, column=0)
video_id=tkin.Label(video_info_frame, text="Video Identifier")
video_id.grid(row=0,column=1)
project_id=tkin.Label(video_info_frame,text="Project ID")
project_id.grid(row=0,column=2)
run_time=tkin.Label(video_info_frame, text="Runtime (Mins)")
run_time.grid(row=0,column=3)

# Setting up entry boxes

video_title_entry=tkin.Entry(video_info_frame)
video_id_entry=tkin.Entry(video_info_frame)
project_id_entry=tkin.Entry(video_info_frame)
run_time_entry=tkin.Entry(video_info_frame)
video_title_entry.grid(row=1,column=0)
video_id_entry.grid(row=1,column=1)
project_id_entry.grid(row=1,column=2)
run_time_entry.grid(row=1,column=3)

for widget in video_info_frame.winfo_children():
    widget.grid_configure(padx=10, pady=5)

# Saving video errors
errors_frame=tkin.LabelFrame(frame,text="Errors Present", padx=20, pady=20)
errors_frame.pack(fill=tkin.BOTH,expand=True)
audiobuzz_check=tkin.Checkbutton(errors_frame,text="Audio Buzz/Hum")
audiocrackle_check=tkin.Checkbutton(errors_frame,text="Audio Crackle")
audiodistortion_check=tkin.Checkbutton(errors_frame,text="Audio Distortion")
audiodrop_check=tkin.Checkbutton(errors_frame,text="Audio Dropout")
audiomuffled_check=tkin.Checkbutton(errors_frame,text="Audio Muffled")
audionoise_check=tkin.Checkbutton(errors_frame,text="Audio Noise")
bearding_check=tkin.Checkbutton(errors_frame, text ="Bearding")
carrier_leak_check=tkin.Checkbutton(errors_frame, text ="Carrier Leak")
color_smearing_check=tkin.Checkbutton(errors_frame, text="Color Smearing")
creased_check=tkin.Checkbutton(errors_frame,text="Creased or Crumpled Tape")
chromnoise_check=tkin.Checkbutton(errors_frame,text="Chrominance Noise")
crosstalk_check=tkin.Checkbutton(errors_frame,text="Crosstalk")
crushed_check=tkin.Checkbutton(errors_frame, text ="Chrushed Setup")
dihedral_check=tkin.Checkbutton(errors_frame,text="Dihedral Maladjustment")
dotcrawl_check=tkin.Checkbutton(errors_frame, text ="Dot Crawl")
dropouts_check=tkin.Checkbutton(errors_frame,text="Dropouts and Dropout Compensation")
egli_check=tkin.Checkbutton(errors_frame, text ="Electrical Ground Loop Interference")
fluorescent_check=tkin.Checkbutton(errors_frame, text ="Fluorescent Strobing")
ghost_check=tkin.Checkbutton(errors_frame, text ="Ghosting")
headclog_check=tkin.Checkbutton(errors_frame,text="Headclogging")
horiHold_check=tkin.Checkbutton(errors_frame,text="Horizontal Hold")
hueError_check=tkin.Checkbutton(errors_frame, text="Hue Error NTSC")
hum_check=tkin.Checkbutton(errors_frame,text="Hum Trouble")
incomp_TVStand=tkin.Checkbutton(errors_frame,text="Incompatibility TV Standards")
incomp_inFam=tkin.Checkbutton(errors_frame,text="Incompatibility in family of formats")
expanshrink_check=tkin.Checkbutton(errors_frame,text="Tape Expansion or Shrinkage")
longPlay_check=tkin.Checkbutton(errors_frame,text="Long Play")
losscolor_check=tkin.Checkbutton(errors_frame,text="Loss of Color Lock")
moire_check=tkin.Checkbutton(errors_frame,text="Moire Effect")
scratchwear_check=tkin.Checkbutton(errors_frame,text="Scratches and Tape Wear")
shiftheadswitch_check=tkin.Checkbutton(errors_frame,text="Shifted Head Switching Point")
skew_check=tkin.Checkbutton(errors_frame,text="Skew Error")
stick_check=tkin.Checkbutton(errors_frame,text="Sticky Tape Syndrome")
stiction_check=tkin.Checkbutton(errors_frame, text ="Stiction")
scpe_check=tkin.Checkbutton(errors_frame, text ="Subcarrier Phase Error")
deform_check=tkin.Checkbutton(errors_frame, text="Tape Deformation")
misalign_check=tkin.Checkbutton(errors_frame,text="Tape Misalignment")
quilting_check=tkin.Checkbutton(errors_frame, text ="Quilting")
ringing_check=tkin.Checkbutton(errors_frame, text ="Ringing")
tBCError_check=tkin.Checkbutton(errors_frame, text="TBC Error")
track_check=tkin.Checkbutton(errors_frame,text="Tracking Error")
vgae_check=tkin.Checkbutton(errors_frame, text ="Vaccum Guide Adjustment Error")
ycdelay_check=tkin.Checkbutton(errors_frame, text ="Y/C Delay Error")
ven_check=tkin.Checkbutton(errors_frame,text="Venetian-Blind Effect PAL")
vhold_check=tkin.Checkbutton(errors_frame,text="Vertical Hold")
vPictJump_check=tkin.Checkbutton(errors_frame,text="Vertical Picture Jumping")
vsync_check=tkin.Checkbutton(errors_frame,text="Vertical Synchronization Error")
visibleFrameLine_check=tkin.Checkbutton(errors_frame, text ="Visble Frame Line")

audiobuzz_check.grid(row=1,column=0)
audiocrackle_check.grid(row=2,column=0)
audiodistortion_check.grid(row=3,column=0)
audiodrop_check.grid(row=4,column=0)
audiomuffled_check.grid(row=5,column=0)
audionoise_check.grid(row=6,column=0)
bearding_check.grid(row=7,column=0)
carrier_leak_check.grid(row=8,column=0)
color_smearing_check.grid(row=9,column=0)
creased_check.grid(row=10,column=0)
chromnoise_check.grid(row=11,column=0)
crosstalk_check.grid(row=12,column=0)
crushed_check.grid(row=1,column=1)
dihedral_check.grid(row=2,column=1)
dotcrawl_check.grid(row=3,column=1)
dropouts_check.grid(row=4,column=1)
egli_check.grid(row=5,column=1)
fluorescent_check.grid(row=6,column=1)
ghost_check.grid(row=7,column=1)
headclog_check.grid(row=8,column=1)
horiHold_check.grid(row=9,column=1)
hueError_check.grid(row=10,column=1)
hum_check.grid(row=11,column=1)
incomp_TVStand.grid(row=12,column=1)
incomp_inFam.grid(row=1,column=2)
expanshrink_check.grid(row=2,column=2)
longPlay_check.grid(row=3,column=2)
losscolor_check.grid(row=4,column=2)
moire_check.grid(row=5,column=2)
scratchwear_check.grid(row=6,column=2)
shiftheadswitch_check.grid(row=7,column=2)
skew_check.grid(row=8,column=2)
stick_check.grid(row=9,column=2)
stiction_check.grid(row=10,column=2)
scpe_check.grid(row=11,column=2)
deform_check.grid(row=12,column=2)
misalign_check.grid(row=1,column=3)
quilting_check.grid(row=2,column=3)
ringing_check.grid(row=3,column=3)
tBCError_check.grid(row=4,column=3)
track_check.grid(row=5,column=3)
vgae_check.grid(row=6,column=3)
ycdelay_check.grid(row=7,column=3)
ven_check.grid(row=8,column=3)
vhold_check.grid(row=9,column=3)
vPictJump_check.grid(row=10,column=3)
vsync_check.grid(row=11,column=3)
visibleFrameLine_check.grid(row=12,column=3)

for widget in errors_frame.winfo_children():
    widget.grid_configure(padx=10, pady=5, sticky="NW")


# Setting up freeform entry

notes_entry_frame=tkin.LabelFrame(frame, text=" Additional Notes", padx=20, pady=20)
notes_entry_frame.pack(fill=tkin.BOTH,expand=True)
notes_entry=tkin.scrolledtext.ScrolledText(notes_entry_frame)
notes_entry.pack(fill=tkin.BOTH,expand=True)


submit_button=tkin.Button(frame,text="Submit", padx=20,pady=20)
submit_button.pack(fill='x')


window.mainloop()