# Building some of the intial variables that will be used
field_names = [
    "Spreadsheet Row Number",
    "work_image",
    "structure",
    "role",
    "work_type",
    "work_accession_number",
    "file_accession_number",
    "filename",
    "label",
    "description",
    "Capture date",
    "Staff Initials",
    "Container number ex. Box Number",
    "folder number",
    "Width (cm.)",
    "Height (cm.)",
    "Date (Year+Month+Day)",
    "project_job_number",
    "Notes about album page or photo",
    "Production Notes",
    "Creator",
    "Source",
    "Copyright Notice",
]
