# Building some of the intial variables that will be used
field_names = [
    "spreadsheet row number",
    "work_image",
    "structure",
    "role",
    "work_type",
    "work_accession_number",
    "file_accession_number",
    "filename",
    "label",
    "description",
    "capture date",
    "staff initials",
    "container number ex. box number",
    "folder number",
    "width (cm.)",
    "height (cm.)",
    "date (year+month+day)",
    "project_job_number",
    "notes about album page or photo",
    "production Notes",
    "creator",
    "source",
    "copyright Notice",
]
